[chipflow]
project_id = 8

[chipflow.steps]
sim = "my_design.steps.sim:MySimStep"
board = "my_design.steps.board:MyBoardStep"
silicon = "my_design.steps.silicon:MySiliconStep"
software = "my_design.steps.software:MySoftwareStep"

[chipflow.silicon]
process = "sky130"
pad_ring = "caravel"

[chipflow.silicon.pads]
sys_clk   = { type = "clk", loc = "0" }
sys_rstn  = { type = "i",   loc = "1" }
uart_tx   = { type = "o",   loc = "2" }
uart_rx   = { type = "i",   loc = "3" }
flash_clk = { type = "o",   loc = "4" }
flash_csn = { type = "o",   loc = "5" }
flash_d0  = { type = "io",  loc = "6" }
flash_d1  = { type = "io",  loc = "7" }
flash_d2  = { type = "io",  loc = "8" }
flash_d3  = { type = "io",  loc = "9" }
gpio_0    = { type = "io",  loc = "10" }
gpio_1    = { type = "io",  loc = "11" }
gpio_2    = { type = "io",  loc = "12" }
gpio_3    = { type = "io",  loc = "13" }
gpio_4    = { type = "io",  loc = "14" }
gpio_5    = { type = "io",  loc = "15" }
gpio_6    = { type = "io",  loc = "16" }
gpio_7    = { type = "io",  loc = "17" }
btn_0     = { type = "io",  loc = "18" }
btn_1     = { type = "io",  loc = "19" }
jtag_tck  = { type = "i",   loc = "33" }
jtag_tms  = { type = "i",   loc = "34" }
jtag_tdi  = { type = "i",   loc = "35" }
jtag_tdo  = { type = "o",   loc = "36" }
